"""Generated by tools/gen_known_holes.py — do not hand-edit.

The SHA-256 of `known_holes.json`, kept in CODE so that editing the data alone cannot
change what doctor believes. Deleting the sidecar cost every capability; emptying it
used to silence every asserted hole for free, which made the cheapest tamper the
profitable one. Now any deviation lands in the same place: `known_holes_source: null`.
"""
KNOWN_HOLES_SHA256 = 'f45e24885e7c8dced88a7e07dccdf722aa1f4d8d39923f88b704c9b67e30c2f3'
