"""Generated by tools/gen_known_holes.py — do not hand-edit.

The SHA-256 of `known_holes.json`, kept in CODE so that editing the data alone cannot
change what doctor believes. Deleting the sidecar cost every capability; emptying it
used to silence every asserted hole for free, which made the cheapest tamper the
profitable one. Now any deviation lands in the same place: `known_holes_source: null`.
"""
KNOWN_HOLES_SHA256 = '629b72f4f52592b65c3a723e0e630d2fdc7e4577834cee2f8f84cd5626006af0'
