"""Generated by tools/gen_known_holes.py — do not hand-edit.

The SHA-256 of `known_holes.json`, kept in CODE so that editing the data alone cannot
change what doctor believes. Deleting the sidecar cost every capability; emptying it
used to silence every asserted hole for free, which made the cheapest tamper the
profitable one. Now any deviation lands in the same place: `known_holes_source: null`.
"""
KNOWN_HOLES_SHA256 = '5f289f1d395ee1fc00fdf26da5fa37ef47efa08b2835d1f9e2adb6fd27ace0fb'
